/*
 * SeminarCatalog Redux
 * Redux bridge for SeminarCatalog API Javascript SDK
 *
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the file manually.
 */

import {createResourceReducer} from './createResourceReducer';
import {createResourceSelectors} from './createResourceSelectors';
import {createResourceActions} from './createResourceActions';
import {reduceCreate, reduceDelete, reduceGet, reduceList, reduceUpdate} from './reducers';

export const createReduxResource = (resource, apiEndpoint) => {
    const actions = createResourceActions(resource, apiEndpoint);
    const reducer = createResourceReducer(resource, actions)
    const selectors = createResourceSelectors(resource);

    return {
        actions,
        reducer,
        selectors
    };
}
