/*
 * SeminarCatalog Redux
 * Redux bridge for SeminarCatalog API Javascript SDK
 *
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the file manually.
 */

import {createAction} from '@reduxjs/toolkit';

export const createAsyncAction = (type, prepareFn = (payload = {}) => payload) => {
    const request   = createAction(`${type}/request`, prepareFn);
    const onSuccess = createAction(`${type}/success`);
    const onFailure = createAction(`${type}/failure`);

    const asyncAction = (payload) => (dispatch) => {
        const response = dispatch(request(payload))

        return response
            .then(data => dispatch(onSuccess(data.value)))
            .catch(data => console.error(data) || dispatch(onFailure(data)));
    }

    asyncAction.type      = type
    asyncAction.toString  = () => type;
    asyncAction.request   = request;
    asyncAction.onSuccess = onSuccess;
    asyncAction.onFailure = onFailure;

    return asyncAction;
}
