/*
 * SeminarCatalog Redux
 * Redux bridge for SeminarCatalog API Javascript SDK
 *
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the file manually.
 */

import {createReducer} from '@reduxjs/toolkit';
import {reduceCreate, reduceDelete, reduceGet, reduceList, reduceUpdate} from './reducers';

export const createEntityReducer = (resource, actions) => createReducer({}, {
    [actions.LIST.onSuccess]: reduceList,
    [actions.GET.onSuccess]: reduceGet,
    [actions.CREATE.onSuccess]: reduceCreate,
    [actions.UPDATE.onSuccess]: reduceUpdate,
    [actions.DELETE.onSuccess]: reduceDelete,
});
