/*
 * SeminarCatalog Redux
 * Redux bridge for SeminarCatalog API Javascript SDK
 *
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the file manually.
 */

import { createSelector } from 'reselect';

const getEntities = (resource) => (state) => state[resource].entities;
const toArray = (resource) => createSelector(
    getEntities(resource),
    Object.values
);

export const createResourceSelectors = (resource) => ({
    getList: toArray(resource),
    getItem: (state, id) => state[resource].entities[id]
});
