/*
 * SeminarCatalog Redux
 * Redux bridge for SeminarCatalog API Javascript SDK
 *
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the file manually.
 */

import {combineReducers} from 'redux';
import {createEntityReducer} from './createEntityReducer';

export const createResourceReducer = (resource, actions) => combineReducers({
    entities: createEntityReducer(resource, actions),
});
