/*
 * SeminarCatalog Redux
 * Redux bridge for SeminarCatalog API Javascript SDK
 *
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the file manually.
 */

import {equals} from 'ramda';

export const reduceList = (state, action) => {
    let resources = {};
    for(const resource of action.payload.entries) {
        resources = {
            ...resources,
            [resource.id]: resource
        }
    }

    if(equals(
        state,
        resources
    )) {
        return undefined;
    }

    return {
        ...state,
        ...resources
    };
};

export const reduceGet = (state, action) => {
    if(equals(
        state[action.payload.id],
        action.payload
    )) {
        return undefined;
    }

    return {
        ...state,
        [action.payload.id]: action.payload
    }
};

export const reduceCreate = (state, action) => {
    return {
        ...state,
        [action.payload.id]: action.payload
    };
};

export const reduceUpdate = (state, action) => {
    if(equals(
        state[action.payload.id],
        action.payload
    )) {
        return undefined;
    }

    return {
        ...state,
        [action.payload.id]: action.payload
    };
};

export const reduceDelete = (state, action) => {
    const _state = {...state};

    if(_state.hasOwnProperty(action.payload)) {
        delete _state[action.payload];
    }

    return {
        ..._state,
    };
};
