/*
 * SeminarCatalog Redux
 * Redux bridge for SeminarCatalog API Javascript SDK
 *
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the file manually.
 */

import {createAsyncAction} from './internal/createAsyncAction';
import {createEntityReducer} from './internal/createEntityReducer';
import {createReduxResource} from './internal/createReduxResource';
import {createResourceActions} from './internal/createResourceActions';
import {createResourceReducer} from './internal/createResourceReducer';
import {createResourceSelectors} from './internal/createResourceSelectors';
import * as reducers from './internal/reducers';
import {ADDRESS} from './resouces/Address';
import {ALLOCATIONWAITINGLIST} from './resouces/AllocationWaitingList';
import {BOOKINGINTEREST} from './resouces/BookingInterest';
import {CATEGORY} from './resouces/Category';
import {CERTIFICATE} from './resouces/Certificate';
import {CONTACTPERSON} from './resouces/ContactPerson';
import {COUNTRY} from './resouces/Country';
import {COUPON} from './resouces/Coupon';
import {COUPONCODE} from './resouces/CouponCode';
import {CURRENCY} from './resouces/Currency';
import {EDUCATIONHISTORYITEM} from './resouces/EducationHistoryItem';
import {EVENT} from './resouces/Event';
import {HOTEL} from './resouces/Hotel';
import {LANGUAGE} from './resouces/Language';
import {LOCATION} from './resouces/Location';
import {MEDIA} from './resouces/Media';
import {ORDER} from './resouces/Order';
import {ORGANIZER} from './resouces/Organizer';
import {PARTICIPANT} from './resouces/Participant';
import {PARTICIPATION} from './resouces/Participation';
import {PARTICIPATIONCODE} from './resouces/ParticipationCode';
import {PARTNER} from './resouces/Partner';
import {PAYMENTMETHOD} from './resouces/PaymentMethod';
import {PRICE} from './resouces/Price';
import {PRODUCT} from './resouces/Product';
import {PRODUCTVARIANT} from './resouces/ProductVariant';
import {PROVIDERINFO} from './resouces/ProviderInfo';
import {RECEIVER} from './resouces/Receiver';
import {REGION} from './resouces/Region';
import {RESTAURANT} from './resouces/Restaurant';
import {REVENUEACCOUNT} from './resouces/RevenueAccount';
import {ROLEDISCOUNT} from './resouces/RoleDiscount';
import {SEMINAR} from './resouces/Seminar';
import {SEMINARCONFIGURATION} from './resouces/SeminarConfiguration';
import {SUBSCRIPTION} from './resouces/Subscription';
import {SUBSCRIPTIONCONFIGURATION} from './resouces/SubscriptionConfiguration';
import {SUBSCRIPTIONPLAN} from './resouces/SubscriptionPlan';
import {TASK} from './resouces/Task';
import {TEST} from './resouces/Test';
import {TESTRESULT} from './resouces/TestResult';
import {TOPIC} from './resouces/Topic';
import {TRAINER} from './resouces/Trainer';
import {USER} from './resouces/User';
import {USERGROUP} from './resouces/UserGroup';
import {VAT} from './resouces/Vat';
import {WAITINGLIST} from './resouces/WaitingList';


export {
    createAsyncAction,
    createEntityReducer,
    createReduxResource,
    createResourceActions,
    createResourceReducer,
    createResourceSelectors,
    reducers,
    ADDRESS,
    ALLOCATIONWAITINGLIST,
    BOOKINGINTEREST,
    CATEGORY,
    CERTIFICATE,
    CONTACTPERSON,
    COUNTRY,
    COUPON,
    COUPONCODE,
    CURRENCY,
    EDUCATIONHISTORYITEM,
    EVENT,
    HOTEL,
    LANGUAGE,
    LOCATION,
    MEDIA,
    ORDER,
    ORGANIZER,
    PARTICIPANT,
    PARTICIPATION,
    PARTICIPATIONCODE,
    PARTNER,
    PAYMENTMETHOD,
    PRICE,
    PRODUCT,
    PRODUCTVARIANT,
    PROVIDERINFO,
    RECEIVER,
    REGION,
    RESTAURANT,
    REVENUEACCOUNT,
    ROLEDISCOUNT,
    SEMINAR,
    SEMINARCONFIGURATION,
    SUBSCRIPTION,
    SUBSCRIPTIONCONFIGURATION,
    SUBSCRIPTIONPLAN,
    TASK,
    TEST,
    TESTRESULT,
    TOPIC,
    TRAINER,
    USER,
    USERGROUP,
    VAT,
    WAITINGLIST
};
