/*
 * SeminarCatalog Redux
 * Redux bridge for SeminarCatalog API Javascript SDK
 *
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the file manually.
 */

import {createReduxResource} from '../internal/createReduxResource';
import {PaymentMethodApi} from '@seminarcatalog/sdk';

export const PAYMENTMETHOD = createReduxResource('paymentmethod', PaymentMethodApi);
